### ISSUE TITLE
http://juanpablofernandez.me

### ISSUE THREAD

**Issue by juanpablofernandez** [soggybag/Front-end-Web-Class-8#1]

**Comment by davidkc0** [comment]
So simple and close to being elegant. The black and white color scheme is nice. You need to center and add animation to the app buttons, and there should be some more color. maybe the social media buttons could be colored when you hover over them?

**Comment by Nkdream** [comment]
I think you should add links to your apps you have made and make sure they are centered. it is solid otherwise

**Comment by outdoorsole** [comment]
Nice site!

Feedback: 
- When hovering over the links of the navigation bar, I noticed that both the currently selected item and the second item are highlighted. Maybe you can use a different color for the new selection (hover state), or have only one navigation item highlighted.
- I would use an icon for your site or different name in place of 'home' (to distinguish it from a portfolio site vs another type of site.
- I like the contrast of the navigation bar with your site colors.

**Comment by tlambrou** [comment]
Great work Jay!  Looks clean and minimalist. 
- It would be great to see a photo of you on the page
- I like your transitions but can't help feeling like they would make even more impact if they were a little slower

**Comment by nonafiona** [comment]
I like the page navigation interaction - when clicking on the nav bar it brings you to a specific spot on the page. You showcase your projects, have an about section, and I like how it concludes with a "contact me" section. 
One thing that could be improved - the font. look at the google font library, it's easy to import & implement into your stylesheets. 
Overall - it looks great dude, I know you've worked really hard on it. 👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻

**Comment by brianhans** [comment]
Good minimalistic design. The about section text is small and isn't as visually appealing as the top one, it seems empty. You should also make the images of your projects link to the app store pages. I like the scrolling animation, it much better than just snapping.

**Comment by soggybag** [comment]
Great work. I really like your personal web site. it works well also, good job. I feel there is still room for improvement with more work! 

You site looks good, but black and white are easy colors to use. Challenge yourself to add some color. I feel this could improve your work. 

The text in the about section is too wide. Think about reducing the width of the paragraph.
