### ISSUE TITLE
http://nicholas-swift.com/newnew/

### ISSUE THREAD

**Issue by Nicholas-Swift** [soggybag/Front-end-Web-Class-8#10]
Please note, still in progress!!!

**Comment by ChandanB** [comment]
Really good layout man! It's one of the nicest that I've seen. Maybe shortcuts could be valuable but besides that, pretty good!

**Comment by nehemiah-io** [comment]
I clicked the submit button but was met with a 404 error other than that I think the site is alright.

**Comment by Hassurunous** [comment]
Good: Clean UI and simple-but-nice layout as you scroll down the page.
Better: Colors on the headers for the various sections are sometimes a bit hard to read, specifically on the black background.
Best: The contact form, social media links, and skills list are great ideas (which I may or may not "take inspiration from" for my next iteration).

**Comment by Saturn-V** [comment]
Good: I dig the feel of the website UI. The layout is simple, and gets straight to the information.

Better: 
- Have a consistent flow.
-  I like how when I first scroll form the first top div, to the div below, it looks like the bottom div rolls on top of the initial div.
- Maybe keep that flow going, such that a every new section (div) you scroll, it just "covers" the dive before it. 
- And you might want to look into making each section (div) have the height of the viewport, so you can say something like height: 100vh, basically saying make this thing as tall as the browser window is. This makes it look cleaner.
- I did notice your images weren't loading as well.

Best: Very nice layout. I like how you are displaying your skills, and showcasing the things you've worked on.

**Comment by Nkdream** [comment]
really dynamic and responsive website. I like the flow of the website.  I think you should make the social media links a little bigger

**Comment by soggybag** [comment]
Great work, this looks really good!
