### ISSUE TITLE
https://github.com/nehemiah-io/Portfolio-site

### ISSUE THREAD

**Issue by nehemiah-io** [soggybag/Front-end-Web-Class-8#12]
私みんなで優しくしてください終了していません。

**Comment by Nicholas-Swift** [comment]
Good:
- Simple, not overly complicated

Better: 
- There should be more padding between the top of the page and your name.
- There should probably be more padding between divs (about, projects, etc..)

Best:
- I love your about info. Very well written. Keep adding to the site and it'll look great!

**Comment by soggybag** [comment]
Looks like a good start. You can do more with this, keep working! The images seemed to be missing? Probably didn't get pushed to Github. Think about the vertical space between elements. Using more space will make the page read better without feeling over crowded. The two project mages are really big and could use some space around the outside. The more you work on this the better it will get. In the future you will have more projects you will want to show. Think about how the future projects will appear on the page.
