### ISSUE TITLE
https://alexander-dejeu.github.io

### ISSUE THREAD

**Issue by alexander-dejeu** [soggybag/Front-end-Web-Class-8#13]
Check it out - Come talk to me!

**Comment by Nicholas-Swift** [comment]
Good:
- I like the colors on the site!

Better:
- The website header where it says 'welcome' might look better if that div is centered in the page.
- When you hover over the cards and they turn grey, the contrast is very striking, considering the whole page is very light.

Best:
- The website is coming along nicely! Keep it up!!

**Comment by nehemiah-io** [comment]
I liked the initial simplicity of the site.
The site when clicking on anything became jarring. I couldn't tell how to exit out of the pop up section
the website is coming along pretty nicely.

**Comment by davidkc0** [comment]
I like the overall layout, but I think you should center the header text.

**Comment by nonafiona** [comment]
The colors are clear and intuitive! The site itself is simplistic & seamless! The only thing I can see that you might want to change is your intro (name, tagline) display the same float position on the left as your Portfolio heading. Nice work, dude 👌🏼

**Comment by soggybag** [comment]
Send me a link to your web site!
