### ISSUE TITLE
https://tlambrou.github.io/tassos.net/

### ISSUE THREAD

**Issue by tlambrou** [soggybag/Front-end-Web-Class-8#16]
https://tlambrou.github.io/tassos.net/

https://github.com/tlambrou/tassos.net

**Comment by alexander-dejeu** [comment]
Cool gradient and picture!  I also like how you have already played around with the typography to include some different styles and weights.  Excited to check this out in the coming days to see the progress.

**Comment by 2bithack** [comment]
love the gradient color on the background and the lamb bro icon is sweet. can't wait to see more content from the html gangster. would like to see some form of page navigation and i look forward to the content.

**Comment by nehemiah-io** [comment]
Is that a goat that you designed cause it is hilarious

Know there will be more content and looks great so far

**Comment by soggybag** [comment]
The first site looks good. I like the color and the icon. These are fun. That link needs a hover and a link color that goes with the rest of the page. Notice the img and the link are sitting in the correct spots. These pages need to each be in their own div or p tag. The omg and a are both inline tags and should be inside of a block tag. Placing each in a block will make sure they stack.
