### ISSUE TITLE
Check out my landing page

### ISSUE THREAD

**Issue by guti7** [soggybag/Front-end-Web-Class-8#17]
https://guti7.github.io

Lay it out.

**Comment by alexander-dejeu** [comment]
Great start!  Maybe consider checking out some typography on Google fonts or somewhere else to add some different weights and styles to your page

**Comment by 2bithack** [comment]
cool website. i love the banksy. can't wait to see more. do you plan to have a single page? or a nav bar? and bump on what dejeu said.

**Comment by tlambrou** [comment]
Looks great Jose!  Perhaps adding some transitions or some sections to create some movement and user engagement.  I really like the stark red amid the black and white.

**Comment by soggybag** [comment]
Nice start. While the image belongs to someone else, with any other artist you might copyright issues. In the case of Banksy I doubt your will hear from their lawyers. 

Think about removing the lines on the left and right of the image. This makes it feel blocked in, where the image feels like it wants to be free and open. You might play with the position. Imagine the image in the lower left of the screen. 

As it is I would suggest some margin on the bottom of the image to push the text down a little further. This would give the image some room.
