### ISSUE TITLE
https://enzobotter.github.io/MJSwebsite/

### ISSUE THREAD

**Issue by 2bithack** [soggybag/Front-end-Web-Class-8#18]
i'm not done yet.. T-T the red circles arent centered correctly. please be gentle.
https://enzobotter.github.io/MJSwebsite/

**Comment by Casey-S** [comment]
Basically the best website 10/10.

For real:
You're going for a sort of minimalist/stylized thing, right? If so, considering I got that impression already, you're on the right track. Gotta fix that header though - dark purple's hard to see against black. Other than that keep it up dude.

**Comment by tlambrou** [comment]
Great work Enzo!  Hey you should consider making some "I went to Enzo's website and all I got were these 3 red dots" t-shirts.   Just kidding. That visited link color needs to change too.  A great start.

**Comment by guti7** [comment]
Good basic layout. 
The console shows two errors with loading support files. It seems like it's coming from missing the script and the icon file.

**Comment by soggybag** [comment]
Looks like a great start. Would be great to have a list of your amazing achievements in there! 

Try 

`body { margin: 0; }`

This will remove the small white space at the top. 

Add a hover style to the links at the top of the page. Speaking  this area might be good to make the black bar extend to the edges of the screen. You can do this by wrapping the grid in a div. You'll need to close the grid around the header, then add another grid around the main part of the page, and the footer. 

```
div.wrap
    div.grid
div.grid
    content
div.wrap
    div.grid
```
