### ISSUE TITLE
https://github.com/Casey-S/Make-School/tree/master/Classes/Front%20End/Personal%20Website

### ISSUE THREAD

**Issue by Casey-S** [soggybag/Front-end-Web-Class-8#20]
https://github.com/Casey-S/Make-School/tree/master/Classes/Front%20End/Personal%20Website

**Comment by soggybag** [comment]
Looks good needs work. This is taking me back to the late 1990s. Good use of text-shadow. You are owning text-shadow. Investigate the blink tag...
