### ISSUE TITLE
https://nonafiona.github.io/

### ISSUE THREAD

**Issue by nonafiona** [soggybag/Front-end-Web-Class-8#21]
m. v. p.    a e s t h e t i c 
( the whitespace above the desk will be a night sky full of stars. ) 
[https://nonafiona.github.io/](https://nonafiona.github.io/)

**Comment by soggybag** [comment]
Looks good. I like the Mac Classic. This type of drawing with CSS is very challenging and there is a lot to learn. I like the colors, these seem to work well, and set a good mood. Keep your color palette in mind as you work. 

Here are a couple suggestions. 

I really want to more content. Add sample of your work to your site. 

1) You used margin to move everything into place. While this is working, you be getting more out of learning to use absolute and relative position here. 

2) Try removing the margin from the body tag. This will remove that small amount of scrolling that happens left to right, and prevent that while space from appearing on the left side. 

`body { margin: 0; }`
