### ISSUE TITLE
https://github.com/brianhans/personalSite

### ISSUE THREAD

**Issue by brianhans** [soggybag/Front-end-Web-Class-8#5]
Live version at: http://www.brianhans.me

**Comment by kojino** [comment]
Good: 
Amazing list of portfolios. I love the color scheme and how it matches with each app. Personally, I think it's better to be colorful than using cold colors and trying to be cool. So, it's great.

Better:
Some of the div layouts are broken, so try to format them using responsive CSS styles.
The link to your app was hard to find, maybe you can make the entire div or the app title a href to the app store.
I don't like the top page ocean background.

Best:
You have the content ready with all the great apps. All you have to is to format it better by putting more spacing and organizing the divs.

**Comment by thanasistratigakis** [comment]
Good: 
- Projects are very clear
- I like all the colors

Suggestions:
- Mention technologies used in each project
- Links to app store/more info
- Obv fix the issue where ur name is off the page in the top right
- Your contact section links to the default email client (a lot of people don't like this). It may be a good idea to leave some contact info in simple text. 
- "Who am I section" - good but I would do it differently.  People are lazy and don't like reading full sentences.  If you can communicate this information in bullet points it may be easier to understand. 
- Fix side scrolling (should only be able to scroll vertically)

**Comment by juanpablofernandez** [comment]
Good site overall,

However I would suggest the following:
- Links should be easier to find
-  Center the arrow that points down on the main view (Center it below your name)
- A bit more margin between views, the transitions are a little rough when scrolling
- I really like the AUX layout maybe you could make the DO O and Coral Glades to look similar (Image on the left, text on the right)

**Comment by Nkdream** [comment]
great website. however you are trying to inject malware into all your website visitors and I am now scared. Are you tracking me now? who knows. but you should fix this problem : 
<img width="1058" alt="screen shot 2016-10-20 at 10 49 55 am" src="https://cloud.githubusercontent.com/assets/17770047/19572295/9c9820ac-96b6-11e6-8b22-97c8a3e96296.png">

**Comment by soggybag** [comment]
This looks really good so far. I like what you have made this is a very effective web site. It can still be improved. 

Think about bringing the pages links in closer together. As is these are spread across the page and get lost. Think about adding hover styles.
