### ISSUE TITLE
http://mrcodecollector.github.io/

### ISSUE THREAD

**Issue by Saturn-V** [soggybag/Front-end-Web-Class-8#8]

**Comment by twof** [comment]
Good: I like the scrolling animation
Better: There ought to be some content
Best: I dig the look and feel

**Comment by Hassurunous** [comment]
Good: The minimalist feel and color palette.
Better: White background seems kind of bland. I think you had it black with white text before, which I liked better. 
Best: The scrolling effect is really nice. Letting other elements organically move onto the page has a nice feel to it.

**Comment by brianhans** [comment]
I like the drop shadow effect on the main content, but it is hard to comment on the overall design because there is much there yet. I like how scrolling down shows "very soon," though.

**Comment by kojino** [comment]
Like the gradient on the div on the left side. The font is very Apple-like and nice.
Add more content, and I can provide you more feedback!

**Comment by soggybag** [comment]
This link didn't work for me: http://mrcodecollector.github.io/ ?
