### ISSUE TITLE
https://twof.github.io/TutoringSite/

### ISSUE THREAD

**Issue by twof** [soggybag/Front-end-Web-Class-8#9]

**Comment by ChandanB** [comment]
Great work. I want to Make Learn With Us now

**Comment by Hassurunous** [comment]
Good: Layout is simple, but looks nice.  
Better: Typeform could use some work to make it pop. 
Best: Flow of information works well and the color palette is clean and crisp.

**Comment by Saturn-V** [comment]
Good: Has good content, simple way to signup.
Better: Top div has inconsistencies in text positioning. Also reduce white space a little.
Best: SICK FLOW DUUUDE. The website has a consistent flow, and it's nice to see information where I expect it to be.

**Comment by brianhans** [comment]
The color scheme and distinct sections help organize the site very well. I would change the font to some sort of sans-serif one which would make it look cleaner. Spacing and graphics could also help make the site appear to have more content and be easier to read. Overall though this is a good base for the tutoring website.

**Comment by soggybag** [comment]
Nice start, keep working this can keep getting better. 

The colored sections are a good idea. Think about adding more space at the top and bottom. The text is center aligned which works for title but doesn't work as well for paragraphs. Trytext-align: justify. 

The title logo looks good but needs more work. 

Style the input field and submit button!
